/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerDashboardRouteImport } from './routes/worker-dashboard'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SdgRouteImport } from './routes/sdg'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiMatchingRouteImport } from './routes/ai-matching'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorkerDashboardRoute = WorkerDashboardRouteImport.update({
  id: '/worker-dashboard',
  path: '/worker-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SdgRoute = SdgRouteImport.update({
  id: '/sdg',
  path: '/sdg',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMatchingRoute = AiMatchingRouteImport.update({
  id: '/ai-matching',
  path: '/ai-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-matching': typeof AiMatchingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sdg': typeof SdgRoute
  '/terms': typeof TermsRoute
  '/worker-dashboard': typeof WorkerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-matching': typeof AiMatchingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sdg': typeof SdgRoute
  '/terms': typeof TermsRoute
  '/worker-dashboard': typeof WorkerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-matching': typeof AiMatchingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sdg': typeof SdgRoute
  '/terms': typeof TermsRoute
  '/worker-dashboard': typeof WorkerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-matching'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/login'
    | '/privacy'
    | '/sdg'
    | '/terms'
    | '/worker-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-matching'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/login'
    | '/privacy'
    | '/sdg'
    | '/terms'
    | '/worker-dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-matching'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/login'
    | '/privacy'
    | '/sdg'
    | '/terms'
    | '/worker-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiMatchingRoute: typeof AiMatchingRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SdgRoute: typeof SdgRoute
  TermsRoute: typeof TermsRoute
  WorkerDashboardRoute: typeof WorkerDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker-dashboard': {
      id: '/worker-dashboard'
      path: '/worker-dashboard'
      fullPath: '/worker-dashboard'
      preLoaderRoute: typeof WorkerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdg': {
      id: '/sdg'
      path: '/sdg'
      fullPath: '/sdg'
      preLoaderRoute: typeof SdgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-matching': {
      id: '/ai-matching'
      path: '/ai-matching'
      fullPath: '/ai-matching'
      preLoaderRoute: typeof AiMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiMatchingRoute: AiMatchingRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SdgRoute: SdgRoute,
  TermsRoute: TermsRoute,
  WorkerDashboardRoute: WorkerDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
